version: '3'
services:
  mongo:
    image: mongo:7.0-rc
    container_name: media.mongo
    ports:
      - "${MONGO_PORT-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - media-network

  redis:
    image: redis:6.2-alpine
    container_name: media.redis
    ports:
      - "${REDIS_PORT-6379}:6379"
    networks:
      - media-network

volumes:
  mongodb_data:

networks:
  media-network:
    name: media-network
    driver: bridge