version: '3'
services:
  #app: 
  #  container_name: media.app
  #  restart: always
  #  build: .
  #  ports:
  #    - "${APP_PORT-3000}:3000"
  #  depends_on:
  #    - mongo
  #    - redis
  mongo:
    image: mongo:7.0-rc
    container_name: media.mongo
    ports:
      - "${MONGO_PORT-27017}:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:6.2-alpine
    container_name: media.redis
    ports:
      - "${REDIS_PORT-6379}:6379"

volumes:
  mongodb_data: